= sssd Atomic container

== Preface

== Using sssd on Atomic Host

The sssd Atomic container is using LABEL to support installation and running
 it easily using the `atomic` tool.

=== Configure sssd

If sssd has already been configured on the Atomic Host, for example
the host was IPA-enrolled, running `atomic install sssd --migrate`
will override the sssd.service definition to start the service in
container via atomic. Existing configuration and data will be re-used.

If sssd hasn't been configured yet, run `atomic install sssd [ options ]`

The options will be passed to `ipa-client-install`, so for example
`atomic install sssd --password the-otp-password`
will attempt to IPA-enroll the machine with the one-time password.

If the options start with word realm, realm (typically realm join)
will be used instead of ipa-client-install: `atomic install sssd realm join [ realm join's options ]`

Options to atomic install can also be specified in the following files
on the host:

[source, bash]
----
   /etc/sssd/ipa-client-install-options - parameters to ipa-client-install
   /etc/sssd/realm-join-options - parameters to realm join
   /etc/sssd/realm-join-password - file with password for realm join
----

When sssd and dependent packages are not installed on the host, at least
the following libraries need to be present there:

[source, bash]
----
   /usr/lib64/libnss_sss.so.2
   /usr/lib64/sssd/modules/sssd_krb5_localauth_plugin.so
   /usr/lib64/libsss_sudo.so
   /usr/lib64/security/pam_sss.so
   /usr/lib64/security/pam_oddjob_mkhomedir.so (for realm join setup)
----

=== Run sssd on Atomic Host

On the Atomic Host, run `atomic run sssd` or the equivalent
`systemctl start sssd.service`.

=== Uninstall

Uninstalling sssd from the Atomic Host will be done by `atomic uninstall sssd`.
